### ISSUE TITLE
Logout button

### ISSUE THREAD

**Issue by riesinger** [riesinger/dhbw-webengineering-project#81]
@leonstern We'd probably need an icon for that 😉

**Comment by christopherpielka** [comment]
Added functionality with commit 08713ea59d163b593f896e0530a3a59e0d08bfc9. Still needs a own icon. Does someone have an idea where I should place the logout button?

**Comment by riesinger** [comment]
@christopherpielka probably to the right of the left/right icons (so in the far right of the toolbar)

**Comment by riesinger** [comment]
@leonstern do you need some inspiration for icons?

**Comment by christopherpielka** [comment]
![logout](https://user-images.githubusercontent.com/39918528/42307035-7400104e-8031-11e8-87df-d0363f3c671c.PNG)
it is like this at the moment (The Trash icon represents the logout). The thing is, the user might click it by accident while trying to navigate on the site if the logout button is located in the upper right corner.

**Comment by riesinger** [comment]
@christopherpielka you could try adding ~48px left margin to the button

**Comment by riesinger** [comment]
you should pull from master btw, our default theme now is red 😉

**Comment by christopherpielka** [comment]
![logout](https://user-images.githubusercontent.com/39918528/42307704-a259a606-8033-11e8-8ca5-4e081bdde06f.PNG)
okay, I added the margin and it now looks way better.
