### ISSUE TITLE
DayView Label is bugged

### ISSUE THREAD

**Issue by christopherpielka** [riesinger/dhbw-webengineering-project#88]
![dayview](https://user-images.githubusercontent.com/39918528/42314255-eed34a8a-8044-11e8-9027-a33905ab7f50.PNG)

**Comment by riesinger** [comment]
Whoopsie, will be fixing ASAP ™️

**Comment by riesinger** [comment]
Or A SAP ™️

**Comment by riesinger** [comment]
Closed by #90
