### ISSUE TITLE
Scrollbar month view

### ISSUE THREAD

**Issue by mariusbartsch** [riesinger/dhbw-webengineering-project#91]
Although the div in the month view containing all day-divs has got the "overflow-y: auto;" property, it won't show a scrollbar if there are too many days in a month to display all. At the bottom you can see, that the days are cut off.

**Comment by mheidinger** [comment]
Let's look into this tomorrow at university 😄

**Comment by riesinger** [comment]
@mariusbartsch could you checkout my changes and see if it works please?

**Comment by mariusbartsch** [comment]
The scrollbar is present and works, but the general header (navigating to day, week etc.) does not work now.

**Comment by mheidinger** [comment]
Closed by #93
